version: "3.3"
services: 
  nginx:
    container_name: nginx
    depends_on:
      - client
      - backend
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 8080:8080
    restart: always

  client:
    container_name: client
    build:
      dockerfile: Dockerfile
      context: ./react-graphql
    volumes: 
      - /app/node_modules
    depends_on:
      - backend
    restart: on-failure

  backend:
    container_name: backend
    build:
      dockerfile: Dockerfile
      context: ./typegraphql-Monolithic-typescript
    volumes:
      - /app/node_modules
    depends_on:
      - mongo
  mongo:
    image: 'mongo'
    container_name: 'mongo'
    ports:
      - '27017:27017'
    environment: 
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes: 
      - ./data/mongo:/data/db